name: Source Code Tests
on: [push]
permissions:
    contents: read
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Skip Duplicate Actions
              uses: fkirc/skip-duplicate-actions@v5.3.0

            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
            - name: Blah
              run: |
                  ls datasets/
            - name: Install dependencies
              run: |
                  pip install ".[dev]"
            - name: Run tests
              run: |
                  pytest
